# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.models.site import Site

class TestSite(unittest.TestCase):
    """Site unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Site:
        """Test Site
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Site`
        """
        model = Site()
        if include_optional:
            return Site(
                id = '01F5A5CRKMZ5BCX9P1S4V990AM',
                nmi = '3052282872',
                channels = [
                    amberelectric.models.channel.Channel(
                        identifier = 'E1', 
                        type = 'general', 
                        tariff = 'A100', )
                    ],
                network = 'Jemena',
                status = 'active',
                active_from = '2022-01-01',
                closed_on = '2022-05-01'
            )
        else:
            return Site(
                id = '01F5A5CRKMZ5BCX9P1S4V990AM',
                nmi = '3052282872',
                channels = [
                    amberelectric.models.channel.Channel(
                        identifier = 'E1', 
                        type = 'general', 
                        tariff = 'A100', )
                    ],
                network = 'Jemena',
                status = 'active',
        )
        """

    def testSite(self):
        """Test Site"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
