# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.models.channel_type import ChannelType

class TestChannelType(unittest.TestCase):
    """ChannelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelType(self):
        """Test ChannelType"""
        # inst = ChannelType()

if __name__ == '__main__':
    unittest.main()
