# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.models.tariff_information import TariffInformation

class TestTariffInformation(unittest.TestCase):
    """TariffInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TariffInformation:
        """Test TariffInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TariffInformation`
        """
        model = TariffInformation()
        if include_optional:
            return TariffInformation(
                period = 'offPeak',
                season = 'default',
                block = 1,
                demand_window = True
            )
        else:
            return TariffInformation(
        )
        """

    def testTariffInformation(self):
        """Test TariffInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
