# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.models.renewable_descriptor import RenewableDescriptor

class TestRenewableDescriptor(unittest.TestCase):
    """RenewableDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenewableDescriptor(self):
        """Test RenewableDescriptor"""
        # inst = RenewableDescriptor()

if __name__ == '__main__':
    unittest.main()
