# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.models.price_descriptor import PriceDescriptor

class TestPriceDescriptor(unittest.TestCase):
    """PriceDescriptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceDescriptor(self):
        """Test PriceDescriptor"""
        # inst = PriceDescriptor()

if __name__ == '__main__':
    unittest.main()
