# coding: utf-8

"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amberelectric.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_current_prices(self) -> None:
        """Test case for get_current_prices

        """
        pass

    def test_get_current_renewables(self) -> None:
        """Test case for get_current_renewables

        """
        pass

    def test_get_prices(self) -> None:
        """Test case for get_prices

        """
        pass

    def test_get_sites(self) -> None:
        """Test case for get_sites

        """
        pass

    def test_get_usage(self) -> None:
        """Test case for get_usage

        """
        pass


if __name__ == '__main__':
    unittest.main()
