from setuptools import setup, find_packages  # noqa: H301

NAME = "amberelectric"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "urllib3 >= 1.25.3",
    "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Amber Electric Public API",
    author="Myles Eftos",
    author_email="myles@madpilot.com.au",
    url="https://github.com/madpilot/amberelectric.py",
    keywords=["Amber Electric Public API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501
    """
)
