"""
    Amber Electric Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from amberelectric.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from amberelectric.model.tariff_information import TariffInformation
    globals()['TariffInformation'] = TariffInformation


class Interval(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('duration',): {
            '5': 5,
            '15': 15,
            '30': 30,
        },
        ('channel_type',): {
            'GENERAL': "general",
            'CONTROLLEDLOAD': "controlledLoad",
            'FEEDIN': "feedIn",
        },
        ('spike_status',): {
            'NONE': "none",
            'POTENTIAL': "potential",
            'SPIKE': "spike",
        },
    }

    validations = {
        ('renewables',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'type': (str,),  # noqa: E501
            'duration': (float,),  # noqa: E501
            'spot_per_kwh': (float,),  # noqa: E501
            'per_kwh': (float,),  # noqa: E501
            'date': (date,),  # noqa: E501
            'nem_time': (datetime,),  # noqa: E501
            'start_time': (datetime,),  # noqa: E501
            'end_time': (datetime,),  # noqa: E501
            'renewables': (float,),  # noqa: E501
            'channel_type': (str,),  # noqa: E501
            'spike_status': (str,),  # noqa: E501
            'tariff_information': (TariffInformation,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'type': 'type',  # noqa: E501
        'duration': 'duration',  # noqa: E501
        'spot_per_kwh': 'spotPerKwh',  # noqa: E501
        'per_kwh': 'perKwh',  # noqa: E501
        'date': 'date',  # noqa: E501
        'nem_time': 'nemTime',  # noqa: E501
        'start_time': 'startTime',  # noqa: E501
        'end_time': 'endTime',  # noqa: E501
        'renewables': 'renewables',  # noqa: E501
        'channel_type': 'channelType',  # noqa: E501
        'spike_status': 'spikeStatus',  # noqa: E501
        'tariff_information': 'tariffInformation',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, type, duration, spot_per_kwh, per_kwh, date, nem_time, start_time, end_time, renewables, channel_type, spike_status, *args, **kwargs):  # noqa: E501
        """Interval - a model defined in OpenAPI

        Args:
            type (str):
            duration (float): Length of the interval in minutes.
            spot_per_kwh (float): NEM spot price. This is the price generators get paid to generate electricity, and what drives the variable component of your perKwh price
            per_kwh (float): Number of cents you will pay per kilowatt-hour (c/kWh)
            date (date): Date the interval belongs to. This may be different to the date component of nemTime, as the last interval of the day ends at 12:30 the following day. Formatted as a ISO 8601 date
            nem_time (datetime): The interval's NEM time. This represents the time at the end of the interval UTC+10. Formatted as a ISO 8601 time
            start_time (datetime): Start time of the interval in UTC. Formatted as a ISO 8601 time
            end_time (datetime): End time of the interval in UTC. Formatted as a ISO 8601 time
            renewables (float): Percentage of renewables in the grid
            channel_type (str): Meter channel type
            spike_status (str): Indicates whether this interval will potentially spike, or is currently in a spike state

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            tariff_information (TariffInformation): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.type = type
        self.duration = duration
        self.spot_per_kwh = spot_per_kwh
        self.per_kwh = per_kwh
        self.date = date
        self.nem_time = nem_time
        self.start_time = start_time
        self.end_time = end_time
        self.renewables = renewables
        self.channel_type = channel_type
        self.spike_status = spike_status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
